config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :todos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
  validates :title, presence: true,
                    length: { minimum: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController

  #   Returns a view page for All Todo Records stores in Database
  #   @@Route: GET: /todos
  #   @@params
  #   @@return
  def index
    @todos = Todo.all
  end

  #   Returns a view page for a Todo Record stores in Database that matches with given id
  #   @@Route: GET: /todos/:id
  #   @@params: :id
  #   @@return
  def show
    @todo = Todo.find(params[:id])
  end

  #   Returns a view page for creating new Todo Record
  #   @@Route: GET: /todos/new
  #   @@params
  #   @@return
  def new
    @todo = Todo.new
  end

  #   Returns a view page for editing a Todo Record that matches with given id
  #   @@Route: GET: /todos/:id/edit
  #   @@params: :id
  #   @@return
  def edit
    @todo = Todo.find(params[:id])
  end

  #   Creates a new Todo Record
  #   @@Route: POST: /todos
  #   @@params: Todo{:title, :details}
  #   @@return
  def create
    # initializing new Todo object with allowed form data
    @todo = Todo.new(todo_create_params)
    # saving the newly instantiated todo object to database
    if @todo.save
      # Successfully saved to database. Now redirecting to view page of newly created Todo
      redirect_to @todo
    else
      # !!!Validation Error occurred. Redirecting back with validation message and input.
      render 'new'
    end
  end

  #   Updates a Todo Record that matches with the given object
  #   @@Route: PATCH: /todos/:id
  #   @@params: Todo{:id, :title, :details, :status}
  #   @@return
  def update
    # Getting a Todo Record that matches with the given id
    @todo = Todo.find(params[:id])
    # Updating the current version of todo object with allowed data
    if @todo.update(todo_update_params)
      # Successfully updated to database. Now redirecting to view page of just updated Todo
      redirect_to @todo
    else
      # !!!Validation Error occurred. Redirecting back with validation message and input.
      render 'edit'
    end
  end

  #   Deletes a Todo Record that matches with the given id
  #   @@Route: Delete: /todos/:id
  #   @@params: :id
  #   @@return
  def destroy
    # Getting a Todo Record that matches with the given id
    @todo = Todo.find(params[:id])
    # Deleting the todo record matched with given id
    @todo.destroy
    redirect_to todos_path
  end


  # Private Block
  # All Helper Functions go here

  private

  #   Returns attributes that are valid for creating new Todo
  #   @@returns: permitted Todo Object
  def todo_create_params
    params.require(:todo).permit(:title, :details)
  end

  #   Returns attributes that are valid for updating existing Todo
  #   @@returns: permitted Todo Object
  def todo_update_params
    params.require(:todo).permit(:title, :details, :status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todos/_form.html.erb
<%= form_with model: @todo, local: true do |form| %>
  <% if @todo.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@todo.errors.count, "error") %> prohibited
        this todo from being saved:
      </h2>
      <ul>
        <% @todo.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :details %><br>
    <%= form.text_area :details %>
  </p>

  <% unless @todo.new_record? %>
    <p>
      <%=  form.check_box :status %>
      <%= form.label :status, "Completed" %>
    </p>
<%  end %>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/todos/edit.html.erb
<h1>Edit Todo</h1>
<%= render 'form' %>

app/views/todos/index.html.erb
<h1>All Todos</h1>
<table>
  <thead>
  <tr>
    <th >Serial </th>
    <th >Title</th>
    <th >Details</th>
    <th >Status</th>
    <th colspan="3">Action</th>
  </tr>
  </thead>
  <tbody>
  <% @todos.each_with_index do |todo, index| %>
  <tr>
    <th><%= index+1 %></th>
    <td><%=  todo.title  %></td>
    <td><%= todo.details %></td>
    <td><%= todo.status==true ?  "Completed" : "Pending" %></td>
    <td><%= link_to 'Show', todo_path(todo) %></td>
    <td><%= link_to 'Edit', edit_todo_path(todo) %></td>
    <td>
      <%= link_to'Delete', todo_path(todo),
                            method:  :delete,
                            data: {confirm: 'Are You sure?'} %>
    </td>
  </tr>
  <% end %>
  </tbody>
</table>

app/views/todos/new.html.erb
<h1>New Todo</h1>
<%=  render 'form' %>
<%= link_to 'Back', todos_path %>

app/views/todos/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @todo.title %>
</p>

<p>
  <strong>Details:</strong>
  <%= @todo.details %>
</p>

<p>
  <strong>Status:</strong>
  <%= @todo.status==true ? "Completed" : "Pending" %>
</p>

<%= link_to 'Back', todos_path %>